# Generated by Django 5.1.7 on 2025-03-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellidos', models.CharField(max_length=50)),
                ('Correo', models.EmailField(max_length=254)),
                ('TipoClientes', models.CharField(max_length=3)),
            ],
        ),
    ]
