# Generated by Django 5.1.7 on 2025-03-22 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='TipoClientes',
            new_name='TipoCliente',
        ),
    ]
