# Generated by Django 5.1.7 on 2025-03-22 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_rename_tipoclientes_cliente_tipocliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mensaje', models.CharField(max_length=50)),
            ],
        ),
    ]
